baseURL = 'http://scytlee.github.io/'
languageCode = 'en-us'
title = 'Pyrewatcher Documentation'

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]